version: 0.2
    
    
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get -y install nfs-common awscli jq dos2unix
      - dos2unix s3download.txt
      - cat s3download.txt
      - . ./s3download.txt
      - mkdir -p $efs_mount_path
